packages:
  - packages/*
  - plugins/*
  - docs

minimumReleaseAgeExclude:
  - "@fraqjs/takumi-builtin-fonts"
  - "@typescript/*"
  - typescript
  - tsdown
  - rolldown-plugin-dts

allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: true
  sharp: true
