packages:
  - packages/*
  - plugins/*
  - docs

minimumReleaseAgeExclude:
  - "@fraqjs/*"
  - "@typescript/*"
  - typescript
  - tsdown
  - rolldown-plugin-dts
  - "@fumadocs/cli"
  - fumadocs-ui

allowBuilds:
  esbuild: true
  sharp: true
