packages:
  - packages/*
  - plugins/*
  - docs
  - "!packages/cli/app"

minimumReleaseAgeExclude:
  - "@fraqjs/*"
  - "@typescript/*"
  - typescript
  - tsdown
  - rolldown-plugin-dts
  - "@fumadocs/cli"
  - fumadocs-ui
  - ai
  - "@ai-sdk/*"

allowBuilds:
  esbuild: true
  sharp: true

ignoreWorkspaceCycles: true
